[build]
target = "browser"
entrypoints = ["./index.html"]
root = "."
publicPath = "/"

[build.minify]
whitespace = true
identifiers = true
syntax = true

[define]
"process.env.NODE_ENV" = "\"production\""

[serve.static]
plugins = ["bun-plugin-tailwind"]